version: '3.9'

services:
    database:
        image: postgres:latest
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=rentalx
        volumes:
            - pgdata:/data/postgres
        networks:
            - development
    app:
        build: .
        container_name: rentalx
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database
        networks:
            - development

volumes:
    pgdata:
        driver: local

networks:
    development:
        driver: bridge